### ISSUE TITLE
[FR] Create LogBoard logo

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/logboard#11]
**Concept**
If we provide LogBoard logo

**Reason/Hypothesis**

We can help users recognize this is the LogBoard service better.

**More Description (if any)**

Put more description here to support the concept

**Suggested Implementation (if any)**

Put some suggested implementation here if you already have some ideas in mind

**Comment by tammyyang** [comment]
Need MyLog marketing to provide the color scheme and logo for LogBoard

Preference of color scheme: black and white with some grey

**Comment by sofiayan0523** [comment]
Done, png & ai see here: https://drive.google.com/drive/u/0/folders/1sYEKxmuEtZDmQXD2nFs4_l9cPVupRlo3
