### ISSUE TITLE
[UI Update] Update Logo and color theme

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/logboard#12]
**Update Purpose**
Update Logo and color theme

**UI Suggestion**

https://github.com/MyDataTaiwan/logboard/issues/11

**More Description (if any)**

Put more description here to help developers understand

**Comment by shc261392** [comment]
There's no description on what to update about the color theme

**Comment by scott-dt** [comment]
logo 更新    color theme 不清楚是什麼

**Comment by scott-dt** [comment]
color theme 沿用 MyLog 的，沒有改
