### ISSUE TITLE
[FR] Enable cron job to cleaning data existing over 72-hour every day.

### ISSUE THREAD

**Issue by bafu** [MyDataTaiwan/logboard#13]
**Suggested Implementation**

Finish the implementation of [feature-clean-database-after-3days](https://github.com/MyDataTaiwan/logboard/tree/feature-clean-database-after-3days).

**Comment by scott-dt** [comment]
5/27, 5/29 連結點開資料還在且可以顯示

**Comment by scott-dt** [comment]
6/5 分享連結點開資料還在

**Comment by scott-dt** [comment]
6/5 link still can show the data in the web
6/12 test link https://logboard-dev.numbersprotocol.io/dashboard/3192c4f5-6c16-4645-821b-eec629f88373 need wait 3 day to cheack

**Comment by scott-dt** [comment]
6/16 open the 6/12 link  https://logboard-dev.numbersprotocol.io/dashboard/3192c4f5-6c16-4645-821b-eec629f88373 still can show the data in the web

**Comment by tammyyang** [comment]
Move to next milestone
