### ISSUE TITLE
[bug report] The temperature chart shows that the time does not match the recorded time

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/logboard#26]
The temperature chart shows that the time does not match the recorded time
![6](https://user-images.githubusercontent.com/62582260/84002616-4ae88980-a99b-11ea-828f-cc1404ab77e5.png)

**Environment**

* mylog14-dashboard: 0.4.1

**Comment by wcchung** [comment]
The time is not match, issue not fixed.

Test date: 2020/6/29 with MyLog v0.10.0

![螢幕快照 2020-06-29 上午10 02 02](https://user-images.githubusercontent.com/12252921/85965614-c57f5480-b9ef-11ea-823e-359a2de7d6ab.png)
