### ISSUE TITLE
[bug report] When the body temperature is below 35 degrees, there is no way to display it

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/logboard#27]
When the body temperature is below 35 degrees, there is no way to display it
![9](https://user-images.githubusercontent.com/62582260/84002766-82573600-a99b-11ea-8093-1089729a75a3.png)

**Environment**

* mylog14-dashboard: 0.4.1

**Comment by wcchung** [comment]
The issue is not fixed.

Test date: 2020/6/29 with MyLog v0.10.0

![螢幕快照 2020-06-29 上午9 57 54](https://user-images.githubusercontent.com/12252921/85965732-3161bd00-b9f0-11ea-81a8-4ad6d07d7ca9.png)
