### ISSUE TITLE
[bug report] The symptom column will display the photo record together

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/logboard#28]
The symptom column will display the photo record together
![7](https://user-images.githubusercontent.com/62582260/84002879-b894b580-a99b-11ea-8148-b96ee5aa2d6b.png)

**Environment**

* mylog14-dashboard: 0.4.1

**Comment by wcchung** [comment]
The issue is not fixed.

Test date: 2020/6/29 with MyLog v0.10.0

![螢幕快照 2020-06-29 上午10 04 52](https://user-images.githubusercontent.com/12252921/85965669-05ded280-b9f0-11ea-9944-1cd110b533d6.png)
