### ISSUE TITLE
[bug report] 資料顯示期間大於2周 症狀欄位會跑版

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/logboard#36]
**Steps to Reproduce**
1. 資料上傳1個月左右的資料
2. 於網頁上切換期間標籤至 " this month "
3. 症狀欄顯示會覆蓋到 calendar 且症狀欄位顯示會消失
![image](https://user-images.githubusercontent.com/62582260/88881648-864c5980-d262-11ea-8987-89d0e0216ef5.png)

**Environment**
* mylog14-dashboard: v 0.5.0
*  Chrome 瀏覽器

**Comment by wcchung** [comment]
@scott-dt Can you provide a screenshot of the issue?

**Comment by scott-dt** [comment]
兩周 & 一個月 的資料在右下角症狀欄位症狀名稱與顯示會錯開
![image](https://user-images.githubusercontent.com/62582260/89364107-5ab6ec80-d704-11ea-83b4-cd3f18bc60ea.png)
![image](https://user-images.githubusercontent.com/62582260/89364124-62769100-d704-11ea-9e6c-c49a4d617965.png)

**Comment by scott-dt** [comment]
v0.1.2 Device: chrome (84.0.4147.105) 沒有錯位現象   Microsoft Edge (84.0.522.52) 還是跟先前一樣

**Comment by wcchung** [comment]
Copy from Slack
@James 既然 release note 上面已經寫了目前支援 Chrome & Firefox，那 #36 就算 close 了。
我會把 Safari & Edge 的支援放到 beta 6
