### ISSUE TITLE
左下方calendar 原本設計會依區間框選目前只會框在當日日期上

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/logboard#37]
**Results**

* Expected: 會依據上方 "this month ,two weeks ,this week "區間按鈕 調整下方calendar 框選區間
* Actual: 目前僅顯示當日日期圓框

**Logs**
![image](https://user-images.githubusercontent.com/62582260/88519206-50ba2d00-d024-11ea-97d9-6513e6e1b42f.png)

**Environment**
* mylog14-dashboard: v 0.5.0
* Chrome 瀏覽器

**Comment by wcchung** [comment]
@scott-dt I think this had been fixed in the latest version? please confirm

**Comment by scott-dt** [comment]
@wcchung 目前是手動調整日期會顯示 如果直接點選上方按鈕無法顯示喔

**Comment by scott-dt** [comment]
目前點選 Today 時 ， 下方calendar 框選區間會停留在上一個顯示的時間區間
![image](https://user-images.githubusercontent.com/62582260/89366078-a9ff1c00-d708-11ea-933a-72edbe2418fe.png)
